//
// Generated file, do not edit! Created by nedtool 5.6 from communication/messages/internal/MobilityCommand.msg.
//

#ifndef __PROJETO_MOBILITYCOMMAND_M_H
#define __PROJETO_MOBILITYCOMMAND_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace projeto {

class MobilityCommand;
} // namespace projeto


namespace projeto {

/**
 * Enum generated from <tt>communication/messages/internal/MobilityCommand.msg:18</tt> by nedtool.
 * <pre>
 * enum MobilityCommandType
 * {
 *     REVERSE = 0;
 * }
 * </pre>
 */
enum MobilityCommandType {
    REVERSE = 0
};

/**
 * Class generated from <tt>communication/messages/internal/MobilityCommand.msg:23</tt> by nedtool.
 * <pre>
 * message MobilityCommand
 * {
 *     MobilityCommandType commandType;
 *     int param1;
 *     int param2;
 *     int param3;
 *     int param4;
 * }
 * </pre>
 */
class MobilityCommand : public ::omnetpp::cMessage
{
  protected:
    projeto::MobilityCommandType commandType = static_cast<projeto::MobilityCommandType>(-1);
    int param1 = 0;
    int param2 = 0;
    int param3 = 0;
    int param4 = 0;

  private:
    void copy(const MobilityCommand& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MobilityCommand&);

  public:
    MobilityCommand(const char *name=nullptr, short kind=0);
    MobilityCommand(const MobilityCommand& other);
    virtual ~MobilityCommand();
    MobilityCommand& operator=(const MobilityCommand& other);
    virtual MobilityCommand *dup() const override {return new MobilityCommand(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual projeto::MobilityCommandType getCommandType() const;
    virtual void setCommandType(projeto::MobilityCommandType commandType);
    virtual int getParam1() const;
    virtual void setParam1(int param1);
    virtual int getParam2() const;
    virtual void setParam2(int param2);
    virtual int getParam3() const;
    virtual void setParam3(int param3);
    virtual int getParam4() const;
    virtual void setParam4(int param4);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MobilityCommand& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MobilityCommand& obj) {obj.parsimUnpack(b);}

} // namespace projeto

#endif // ifndef __PROJETO_MOBILITYCOMMAND_M_H

